version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ec2-user/node-website
  - source: /config.js
    destination: /home/ec2-user/node-website
  - source: /package.json
    destination: /home/ec2-user/node-website
  - source: /public/
    destination: /home/ec2-user/node-website/public
  - source: /node_modules/
    destination: /home/ec2-user/node-website/node_modules
  - source: /bin/
    destination: /home/ec2-user/node-website/bin
  - source: /scripts/
    destination: /home/ec2-user/node-website/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
